ALTER TABLE "Quotation"
ADD COLUMN "partCount" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "QuotationItem"
ADD COLUMN "partNumber" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "activityDays" INTEGER NOT NULL DEFAULT 1;
