FROM node:22-bullseye

WORKDIR /app
COPY package.json ./
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      openssl ca-certificates \
      fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libcairo2 \
      libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libglib2.0-0 \
      libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 \
      libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxext6 \
      libxfixes3 libxrandr2 libxshmfence1 && \
    rm -rf /var/lib/apt/lists/* && \
    npm install
COPY . .
RUN npx prisma generate && npm run build

EXPOSE 5001
CMD ["npm", "run", "start"]
